server:
  port: 54465
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:shopifydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000} # 1 day

shopify:
  client-id: ${SHOPIFY_CLIENT_ID}
  client-secret: ${SHOPIFY_CLIENT_SECRET}